Module2 task1
htmlacademy-adaptive/1934253-cat-energy-25 pull request #2
Opened 2022-04-05 13:18 UTC by DenisDenis1991

2022-04-09 11:11 UTC, GennadiyM requested changes

2022-04-09 11:11 UTC, GennadiyM commented on desktop.ini
> +[.ShellClassInfo]
что за файл?

2022-04-09 11:11 UTC, GennadiyM commented on source/index.html
>      <title>HTML Academy: Кэт энерджи</title>
почитай критерии тут не хватает атрибута адаптивности

2022-04-09 11:11 UTC, GennadiyM commented on source/index.html
> +          <img src="../source/img/icons/logo-mobile.svg" width="34" height="38" alt="Логотип Кэт Энерджи">
а что за путь а картинки? откуда в нем появилась папка source? в билде проекта ее не будет

2022-04-09 11:11 UTC, GennadiyM commented on source/index.html
> +          <button class="button-menu" type="button">
class="togge" (общепринятое название)

2022-04-09 11:11 UTC, GennadiyM commented on source/index.html
> +      <div class="page__wrapper">
class="page__wrapper header__wrapper" очень большая вероятность, что здесь нужно будет миксовать

2022-04-09 11:11 UTC, GennadiyM commented on source/index.html
> +            <span class="visually-hidden">Меню</span>
перенеси в aria-label. давай пользоваться современными методами и не "сорить" в разметке лишними блоками

2022-04-09 11:11 UTC, GennadiyM commented on source/index.html
> +          <button class="button-menu" type="button">
Каким боком кнопка открытия и закрытия меню относится к главной навигации? графически? так у нас для графической привязки есть css и вариации оберток. Убрать ее из тега nav

2022-04-09 11:11 UTC, GennadiyM commented on source/index.html
> +        </section>
Этот блок к шапке не имеет никакого отношения. Убрать в main

2022-04-09 11:11 UTC, GennadiyM commented on source/index.html
> +          <h2 class="promo__title promo-title">Функциональное питание для котов</h2>
зачем ему миксование классов?  class="promo__title">Функциональное питание для котов
на данном этапе достаточно этого

2022-04-09 11:11 UTC, GennadiyM commented on source/index.html
> +          <p class="promo__description promo-description">Занялся собой? Займись котом!</p>
убрать миксование

2022-04-09 11:11 UTC, GennadiyM commented on source/index.html
> +            <img class="image" src="../source/img/promo/product1.png" width="280" height="270" alt="Кэт-энерджи про">
что за название у картинки?

2022-04-09 11:11 UTC, GennadiyM commented on source/index.html
> +          <a class="promo__button promo-button" href="#nowhere">Подобрать программу</a>
убрать миксование

2022-04-09 11:11 UTC, GennadiyM commented on source/index.html
> +    <main class="page__main main">
не понадобится отлеьный класс main - убрать миксование

2022-04-09 11:11 UTC, GennadiyM commented on source/index.html
> +          <h2 class="visually-hidden">каталог слим</h2>
убрать отюда

2022-04-09 11:11 UTC, GennadiyM commented on source/index.html
> +          <a class="slim__link article-link" href="#nowhere">Каталог slim</a>
ссылкой можно обернуть заголовок

2022-04-09 11:11 UTC, GennadiyM commented on source/index.html
> +          <h2 class="about__heading heading">Как это работает?</h2>
вот тут я согласен с миксованием

2022-04-09 11:11 UTC, GennadiyM commented on source/index.html
> +              <p class="about-list__description main-text">Функциональное питание содержит только полезные питательные вещества.</p>
что делает main-text? если он задает шрифтовые параметры для текста отличные от того что ты задаш в body - оставляй, в противном случае убирай

2022-04-09 11:11 UTC, GennadiyM commented on source/index.html
> +              <p class="about-list__description main-text">Выпускается в виде порошка, который нужно лишь залить кипятком и готово.</p>
зачем здесь параграфы? просто оборачиваешь текст в li

2022-04-09 11:11 UTC, GennadiyM commented on source/index.html
> +          <b class="example__cost example-text"> 15 000 РУБ.</b>
что за пробел до цифр

2022-04-09 11:11 UTC, GennadiyM commented on source/index.html
> +            <span class="range__before slider-text">Было</span>
а что было и стало не будут ораганими управления на десткопе? вообще блок требует глубокого пересмотрения

2022-04-09 11:11 UTC, GennadiyM commented on source/index.html
> +        <address class="contact__address address-text">ул. Большая Конюшенная, д. 19/8 Санкт-Петербург</address>
опять ненужные миксования

2022-04-09 11:11 UTC, GennadiyM commented on source/index.html
> +        </ul>
а с чего это вдруг список? это обычная ссылка на академию

2022-04-12 13:16 UTC, DenisDenis1991 commented on source/index.html
> +        <address class="contact__address address-text">ул. Большая Конюшенная, д. 19/8 Санкт-Петербург</address>
у текста приглашения и адреса, разные размеры шрифта

2022-04-14 15:06 UTC, GennadiyM requested changes

2022-04-14 15:06 UTC, GennadiyM commented on source/index.html
> +          <b class="slim__title title slim__title--slim-img">Похудение</b>
заголовок

2022-04-14 15:06 UTC, GennadiyM commented on source/index.html
> +        </article>
оберни их в список

2022-04-14 15:06 UTC, GennadiyM commented on img/README
> +Изображение htmlacademy.svg — это логотип Академии. Другие варианты логотипа можно забрать из репозитория https://github.com/htmlacademy/logo.
зачем две иконки академии?

2022-04-14 15:06 UTC, GennadiyM commented on source/index.html
> +          <img src="../img/icons/logo-mobile.svg" width="34" height="38" alt="Логотип Кэт Энерджи">
странный путь к картинке используй src="img/
а вот в css да "../ надо будет подняться на папку выше

2022-04-14 15:06 UTC, GennadiyM commented on source/index.html
> +      <h1 class="visually-hidden">Магазин функционального питания Кэт Энерджи</h1>
ну поставь его уже под main

2022-04-14 15:06 UTC, GennadiyM commented on source/index.html
> +          <img src="../img/promo/product1.png" width="280" height="270" alt="Кэт-энерджи про">
адрес

2022-04-14 15:06 UTC, GennadiyM commented on source/index.html
> +        <a class="promo__button" href="#nowhere">Подобрать программу</a>
promo__btn btn
у тебя очень много таких кнопок в проекте. ЛОгично сделать их блоком. btn - общепринятое сокращение

2022-04-14 15:06 UTC, GennadiyM commented on source/index.html
> +        </article>
оберни их в список ul.

2022-04-14 15:06 UTC, GennadiyM commented on source/index.html
> +          <b class="pro__title title pro__title--pro-img">Набор массы</b>
заголовок.  раз сделал архивом

2022-04-14 15:06 UTC, GennadiyM commented on source/index.html
> +          <a class="pro__link article-link" href="#nowhere">Каталог pro</a>
а вот тут article-link лишнее. Кнопка только в этом блоке есть

2022-04-14 15:06 UTC, GennadiyM commented on source/index.html
> +        <article class="slim">
silm--модификатор. С текста убери модификаторы. У тебя есть отрисовка,  когда картинка отвеязана от заголовка. Тут надо будет через двойные селекторы на них влиять (от модификатора родителя)

2022-04-14 15:06 UTC, GennadiyM commented on source/index.html
> +        <address class="contact__address address-text">ул. Большая Конюшенная, д. 19/8 Санкт-Петербург</address>
я так понимаю ты не загрузил изменения. оберни санкт петербург в спан. иначе не получится сделать такой отступ как в макете

2022-04-14 15:06 UTC, GennadiyM commented on source/index.html
> +        <div class="contact__map map-img">
лишнее миксование классов

2022-04-14 15:06 UTC, GennadiyM commented on source/index.html
> +          <img src="../img/map/map.jpg" width="320" height="360" alt="ул. Большая Конюшенная, д. 19/8 Санкт-Петербург">
адрес картинки

2022-04-14 15:06 UTC, GennadiyM commented on source/index.html
> +        </a>
это все одна ссылка

2025-03-02 14:33 UTC, closed without merging